version: '3'

networks:
  web:
    external: true
  internal:
    external: false


services:
  website:
    container_name: curilux-admin
    build:
      context: .
      dockerfile: Dockerfile
    labels:
      - traefik.http.routers.curilux_adm.rule=Host(`curiluxadm.edalytics.com`)
      - traefik.http.routers.curilux_adm.tls=true
      - traefik.http.routers.curilux_adm.tls.certresolver=lets-encrypt
      - traefik.port=80
    networks:
      - web
      - internal
